CREATE SCHEMA EMPRESA_AEREA;

USE EMPRESA_AEREA;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
	PASS_CPF VARCHAR(14) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_RUA VARCHAR(100) NOT NULL,
	PASS_NUMRUA INT,
	PASS_BAIRRO VARCHAR(50) NOT NULL,
	PASS_CIDADE VARCHAR(50) NOT NULL,
	PASS_ESTADO VARCHAR(50) NOT NULL,
	PASS_PAIS VARCHAR(50) NOT NULL,
	PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS (
	VOO_ID INT PRIMARY KEY,
    
);


CREATE TABLE IF NOT EXISTS RESERVAS (
	RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT PRIMARY KEY,
    PASS_CPF VARCHAR(14) PRIMARY KEY,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);