CREATE SCHEMA EST_CASO_V;

USE EST_CASO_V;

-- Tabela CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
	CLI_CPF VARCHAR(14) PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_RUA VARCHAR(50),
    CLI_NUMRUA VARCHAR(25) NOT NULL,
    CLI_BAIRRO VARCHAR(50) NOT NULL,
    CLI_CIDADE VARCHAR(50) NOT NULL,
    CLI_UF CHAR(2) NOT NULL,
    CLI_PAIS VARCHAR(100) NOT NULL,
    CLI_CEP VARCHAR(15) NOT NULL,
    CLI_STATUS_PROMO ENUM("APROVADO", "REPROVADO") NOT NULL
);

-- Tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FORN_CNPJ VARCHAR(50) PRIMARY KEY,
    FORN_NOME VARCHAR(100) NOT NULL,
    FORN_TELEFONE VARCHAR(16) NOT NULL,
    FORN_EMAIL VARCHAR(50) NOT NULL
);

-- Tabela PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
	PROD_ID INT PRIMARY KEY,
    PROD_CATEGORIA VARCHAR(50) NOT NULL,
    PROD_QTDDISPONIVEL INT NOT NULL,
	PROD_PRECO DECIMAL(10, 3) NOT NULL
);

-- Tabela associativa entre PRODUTOS <-> FORNECEDORES
CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES (
	PROD_ID INT,
    FORN_CNPJ VARCHAR(50),
    PRIMARY KEY(PROD_ID, FORN_CNPJ),
    -- FK vinda da tabela PRODUTOS
    CONSTRAINT PRFO_FK_PRODUTOS FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS(PROD_ID),
        -- FK vinda da tabela FORNECEDORES
    CONSTRAINT PRFO_FK_FORNECEDORES FOREIGN KEY(FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

-- Tabela PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
	PAG_ID INT PRIMARY KEY,
    PAG_DATA DATE NOT NULL,
    PAG_HORA TIME NOT NULL,
    PAG_VALOR DECIMAL (10,3) NOT NULL,
    PAG_STATUS ENUM("PENDENTE", "PAGO", "CANCELADO")
);

-- Tabela VENDAS
CREATE TABLE IF NOT EXISTS VENDAS (
	VENDA_ID INT PRIMARY KEY,
    CLI_CPF VARCHAR(14) NOT NULL,
    PAG_ID INT NOT NULL,
    -- FK vinda da tabela CLIENTES
    CONSTRAINT VENDA_FK_CLIENTES FOREIGN KEY(CLI_CPF) REFERENCES CLIENTES(CLI_CPF),
    -- FK vinda da tabela PAGAMENTOS
    CONSTRAINT VENDA_FK_PAGAMENTOS FOREIGN KEY(PAG_ID) REFERENCES PAGAMENTOS(PAG_ID)
);

-- Tabela associativa entre VENDAS <-> PRODUTOS
CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
	VENDA_ID INT,
    PROD_ID INT,
    PRIMARY KEY(VENDA_ID, PROD_ID),
    VEPRO_QTD_VENDIDA INT NOT NULL,
    VEPRO_VALORTOTAL DECIMAL(10,3) NOT NULL,
    -- FK vinda da tabela PRODUTOS
    CONSTRAINT VEPRO_FK_PRODUTOS FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS(PROD_ID),
    -- FK vinda da tabela VENDAS
    CONSTRAINT VEPRO_FK_VENDAS FOREIGN KEY(VENDA_ID) REFERENCES VENDAS(VENDA_ID)
);

-- ###################################################### --
-- ##################### ALTERS ######################### --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

--  ALTERS da tabela CLIENTES

-- ADD COLUMN
ALTER TABLE CLIENTES ADD CLI_NOMEDAMAE VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CLIENTES MODIFY COLUMN CLI_NOMEDAMAE VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE CLIENTES CHANGE COLUMN CLI_NOMEDAMAE CLI_NOMEMAE VARCHAR(100);

-- DROP COLUMN
ALTER TABLE CLIENTES DROP COLUMN CLI_NOMEMAE;

------------------------------------------------------------------------------

--  ALTERS da tabela FORNECEDORES

-- ADD COLUMN
ALTER TABLE FORNECEDORES ADD FORN_PAIS VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_PAIS VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_PAIS FORN_PAISORIGEM TEXT;

-- DROP COLUMN
ALTER TABLE FORNECEDORES DROP COLUMN FORN_PAISORIGEM;

------------------------------------------------------------------------------

--  ALTERS da tabela FORNECEDORES

-- ADD COLUMN
ALTER TABLE FORNECEDORES ADD FORN_PAIS VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_PAIS VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_PAIS FORN_PAISORIGEM TEXT;

-- DROP COLUMN
ALTER TABLE FORNECEDORES DROP COLUMN FORN_PAISORIGEM;

------------------------------------------------------------------------------

--  ALTERS da tabela PRODUTOS

-- ADD COLUMN
ALTER TABLE PRODUTOS ADD PROD_ORIGEMPROD VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_ORIGEMPROD VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_ORIGEMPROD PROD_ORIGEM TEXT;

-- DROP COLUMN
ALTER TABLE PRODUTOS DROP COLUMN PROD_ORIGEM;

------------------------------------------------------------------------------

--  ALTERS da tabela PRODUTOS_FORNECEDORES

-- ADD COLUMN
ALTER TABLE PRODUTOS_FORNECEDORES ADD PRFO_QUANTIDADE VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PRODUTOS_FORNECEDORES MODIFY COLUMN PRFO_QUANTIDADE INT;

-- CHANGE COLUMN
ALTER TABLE PRODUTOS_FORNECEDORES CHANGE COLUMN PRFO_QUANTIDADE PRFO_QTD INT;

-- DROP COLUMN
ALTER TABLE PRODUTOS_FORNECEDORES DROP COLUMN PRFO_QTD;

------------------------------------------------------------------------------

--  ALTERS da tabela PAGAMENTOS

-- ADD COLUMN
ALTER TABLE PAGAMENTOS ADD PAG_MODALIDADE VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_MODALIDADE ENUM("PIX", "CREDITO", "DEBITO", "BOLETO");

-- CHANGE COLUMN
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_MODALIDADE PAG_MOD ENUM("PIX", "CREDITO", "DEBITO", "BOLETO");

-- DROP COLUMN
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_MOD;

------------------------------------------------------------------------------

--  ALTERS da tabela VENDAS

-- ADD COLUMN
ALTER TABLE VENDAS ADD VENDA_DATA VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE VENDAS MODIFY COLUMN VENDA_DATA DATE;

-- CHANGE COLUMN
ALTER TABLE VENDAS CHANGE COLUMN VENDA_DATA VENDA_DATAVENDA DATE;

-- DROP COLUMN
ALTER TABLE VENDAS DROP COLUMN VENDA_DATAVENDA;

------------------------------------------------------------------------------

--  ALTERS da tabela VENDAS_PRODUTOS

-- ADD COLUMN
ALTER TABLE VENDAS_PRODUTOS ADD VDPRO_HORA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE VENDAS_PRODUTOS MODIFY COLUMN VDPRO_HORA TIME;

-- CHANGE COLUMN
ALTER TABLE VENDAS_PRODUTOS CHANGE COLUMN VDPRO_HORA VDPRO_HR TIME;

-- DROP COLUMN
ALTER TABLE VENDAS_PRODUTOS DROP COLUMN VDPRO_HR;


-- ###################################################### --
-- ######################## DROP ######################## --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

DROP TABLE CLIENTES, FORNECEDORES, PRODUTOS, PRODUTOS_FORNECEDORES, PAGAMENTOS, VENDAS, VENDAS_PRODUTOS CASCADE;



