-- FASE 1: CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE):
-- MEU PRIMEIRO BANQUINHO
CREATE SCHEMA EC1_CC1N;

-- FASE 2: SELECIONAR O NOVO SCHEMA OU DATABASE PARA USO:
-- USANDO MEU BANQUINHO
USE EC1_CC1N;


-- FASE 3: CRIANDO AS TABELAS SEM CHAVES ESTRANGEIRAS

-- CRIANDO A TABELINHA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#NOMEDOATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE(OPCIONAL)
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

-- CRIANDO A TABELINHA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL);

-- CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

-- FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA

-- CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

-- CRIANDO A TABELA RECEBIMENTOS (VEIO DEPOIS POIS TEM DEPENDÊNCIA DE PEDIDOS)
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

-- FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)

-- CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS,PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

-- CRIANDO A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD));

-- CRIAR A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));



-- ###################################################### --
-- ##################### ALTERS ######################### --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --



--  ALTERS da tabela FORNECEDORES

-- ADD COLUMN
ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(100) NOT NULL;

-- DROP COLUMN
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_CONTATO;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES MODIFY COLUMN NOME VARCHAR(150);

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNEC_NOME FORNEC_NOMECOMPLETO VARCHAR(150);

----------------------------------------------------------------------------

--  ALTERS da tabela FILIAIS

-- ADD COLUMN
ALTER TABLE FILIAIS ADD FILIAL_CEP VARCHAR(14) NOT NULL;

-- DROP COLUMN
ALTER TABLE FILIAIS DROP COLUMN FILIAL_CODPOSTAL;

-- MODIFY COLUMN
ALTER TABLE FILIAIS MODIFY COLUMN FILIAL_NUMRUA VARCHAR(50);

-- CHANGE COLUMN
ALTER TABLE FILIAIS CHANGE COLUMN FILIAL_NUMRUA FILIAL_NUM VARCHAR(50);

----------------------------------------------------------------------------

--  ALTERS da tabela PRODUTOS

-- ADD COLUMN
ALTER TABLE PRODUTOS ADD PROD_CATEGORIA VARCHAR(100) NOT NULL;

-- DROP COLUMN
ALTER TABLE PRODUTOS DROP COLUMN PROD_ESPECTEC;

-- MODIFY COLUMN
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_DESCRICAO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_PRECOUNIT PROD_PRECOUNITARIO  DECIMAL(10,2);


----------------------------------------------------------------------------

--  ALTERS da tabela PEDIDOS

-- ADD COLUMN
ALTER TABLE PEDIDOS ADD PED_PREVISAOHORA TIME;

-- DROP COLUMN
ALTER TABLE PEDIDOS DROP COLUMN PED_HORA;

-- MODIFY COLUMN
ALTER TABLE PEDIDOS MODIFY COLUMN PED_STATUS VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE PEDIDOS CHANGE COLUMN PED_PREVISAO PRED_PREVISAOCHEGADA TIME;

----------------------------------------------------------------------------

--  ALTERS da tabela RECEBIMENTOS

-- ADD COLUMN
ALTER TABLE RECEBIMENTOS ADD RECEB_TIPOEMBALAGEM VARCHAR(100) NOT NULL;

-- DROP COLUMN
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_CONDICAO;

-- MODIFY COLUMN
ALTER TABLE RECEBIMENTOS MODIFY COLUMN RECEB_QUANT_PROD DECIMAL(10, 2);

-- CHANGE COLUMN
ALTER TABLE RECEBIMENTOS CHANGE COLUMN RECEB_QUANT_PROD RECEB_QUANT DECIMAL(10, 2);


----------------------------------------------------------------------------

--  ALTERS da tabela PEDIDOS_PRODUTOS

-- ADD COLUMN
ALTER TABLE PEDIDOS_PRODUTOS ADD PDPR_VALORTOTAL DECIMAL(10, 3) NOT NULL;

-- DROP COLUMN
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PDPR_VALORTOTAL;

-- MODIFY COLUMN
ALTER TABLE PEDIDOS_PRODUTOS MODIFY COLUMN PDPR_QUANT DECIMAL(10, 2);

-- CHANGE COLUMN
ALTER TABLE PEDIDOS_PRODUTOS CHANGE COLUMN PDPR_QUANT PDPR_QUANTIDADE DECIMAL(10, 2);

----------------------------------------------------------------------------

--  ALTERS da tabela FILIAIS_PRODUTOS

-- ADD COLUMN
ALTER TABLE FILIAIS_PRODUTOS ADD FLPR_VALORTOTAL DECIMAL(10, 3) NOT NULL;

-- DROP COLUMN
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FLPR_VALORTOTAL;

-- MODIFY COLUMN
ALTER TABLE FILIAIS_PRODUTOS MODIFY COLUMN FLPR_QUANT DECIMAL(10, 2);

-- CHANGE COLUMN
ALTER TABLE FILIAIS_PRODUTOS CHANGE COLUMN FLPR_QUANT FLPR_QUANTIDADE DECIMAL(10, 2);

----------------------------------------------------------------------------

--  ALTERS da tabela FORNECEDORES_PRODUTOS

-- ADD COLUMN
ALTER TABLE FORNECEDORES_PRODUTOS ADD FRPR_VALORTOTAL DECIMAL(10, 3) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY COLUMN FRPR_VALORTOTAL DECIMAL(10, 2);

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE COLUMN FRPR_VALORTOTAL FRPR_TOTALVALOR DECIMAL(10, 2);

-- DROP COLUMN
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FRPR_TOTALVALOR;


-- ###################################################### --
-- ######################## DROP ######################## --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

DROP TABLE RECEBIMENTOS;