CREATE SCHEMA EST_CASO_III;

USE EST_CASO_III;

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO (
	TIPO_END_COD INT PRIMARY KEY,
    TIPO_END_CATEGORIA VARCHAR(45)
);

-- Tabela ENDERECOS
CREATE TABLE IF NOT EXISTS ENDERECOS (
	END_COD INT PRIMARY KEY,
    END_LOGRADOURO VARCHAR(100) NOT NULL,
    END_NUM VARCHAR(45),
    END_BAIRRO VARCHAR(45) NOT NULL,
    END_CIDADE VARCHAR(45) NOT NULL,
    END_UF CHAR(2) NOT NULL,
    END_CEP VARCHAR(20) NOT NULL,
    -- Chave estrangeira vinda da tabela TIPO_ENDERECO
    TIPO_END_COD INT NOT NULL,
    CONSTRAINT FK_TIPO_ENDERECOS FOREIGN KEY(TIPO_END_COD) REFERENCES TIPO_ENDERECO(TIPO_END_COD)
);

-- Tabela EMPRESAS
CREATE TABLE IF NOT EXISTS EMPRESAS (
	EMPRE_COD INT PRIMARY KEY,
    EMPRE_CNPJ VARCHAR(45) NOT NULL,
    EMPRE_RAZAOSOCIAL VARCHAR(100) NOT NULL,
    EMPRE_PCONTATO VARCHAR(45) NOT NULL,
    -- Chave estrangeira vinda da tabela ENDERECOS
    EMPRE_END_COD INT NOT NULL UNIQUE,
    CONSTRAINT FK_ENDERECOS FOREIGN KEY(EMPRE_END_COD) REFERENCES ENDERECOS(END_COD)
);

-- Tabela EMPRE_TEL
CREATE TABLE IF NOT EXISTS EMPRE_TEL (
	EMPRE_COD INT PRIMARY KEY,
    EMPRE_TEL_TELEFONE VARCHAR(45) NOT NULL,
    -- Chave estrangeira que também é PK vinda da tabela EMPRESAS
    CONSTRAINT FK_EMPRESAS FOREIGN KEY(EMPRE_COD) REFERENCES EMPRESAS(EMPRE_COD) 
);

-- Tabela CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
	CLI_COD INT PRIMARY KEY,
    CLI_CNPJ VARCHAR(45) NOT NULL,
    CLI_RAZAOSOCIAL VARCHAR(45) NOT NULL,
    CLI_RAMOATIV VARCHAR(45) NOT NULL,
    CLI_PCONTATO VARCHAR(45) NOT NULL,
    CLI_DATACADAS VARCHAR(45) NOT NULL
);

-- Tabela CLI_TEL
CREATE TABLE IF NOT EXISTS CLI_TEL (
	CLI_COD INT PRIMARY KEY,
    CLI_TEL_TELEFONE VARCHAR(45) NOT NULL,
    -- Chave estrangeira que também é PK vinda da tabela CLIENTES
    CONSTRAINT FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD) 
);

-- ENTIDADE ASSOCIATIVA ENTRE CLIENTES <-> ENDERECOS
CREATE TABLE IF NOT EXISTS CLIENTES_ENDERECOS (
	CLI_COD INT NOT NULL,
    CLI_END_COD INT NOT NULL,
	PRIMARY KEY(CLI_COD, CLI_END_COD),
    -- Chaves PK e FK
    CONSTRAINT CLEN_FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD),
    CONSTRAINT CLEN_FK_ENDERECOS FOREIGN KEY(CLI_END_COD) REFERENCES ENDERECOS(END_COD)
);

-- Tabela CARGOS
CREATE TABLE IF NOT EXISTS CARGOS (
	CARGOS_COD INT PRIMARY KEY,
    CARGO_NOME VARCHAR(50) NOT NULL,
    CARGO_SALARIO DECIMAL(10,2) NOT NULL
);

-- Tabela FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	FUNC_MATRICULA INT PRIMARY KEY,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATAADMISSAO DATE NOT NULL,
    -- Chave estrangeira vinda da tabela CARGO
    FUNC_CARGO_COD INT NOT NULL,
    -- Chave estangeira vinda da tabela ENDERECOS
    FUNC_END_COD INT NOT NULL,
    CONSTRAINT FUNC_FK_CARGO FOREIGN KEY(FUNC_CARGO_COD) REFERENCES CARGOS(CARGOS_COD),
    CONSTRAINT FUNC_FK_ENDERECOS FOREIGN KEY(FUNC_END_COD) REFERENCES ENDERECOS(END_COD)
);

-- Tabela QUALIFICACOES
CREATE TABLE IF NOT EXISTS QUALIFICACOES (
	FUNC_MATRICULA INT PRIMARY KEY,
    QUALIFICACAO_FUNC TEXT,
    CONSTRAINT QUALIFICACOES_FK_FUNC FOREIGN KEY(FUNC_MATRICULA) REFERENCES FUNCIONARIOS(FUNC_MATRICULA)
);

-- Tabela FUNC_TEL
CREATE TABLE IF NOT EXISTS FUNC_TEL (
	FUNC_MATRICULA INT PRIMARY KEY,
    FUNC_TEL VARCHAR(15) NOT NULL,
    -- Chave estangeira vinda da tabela FUNCIONARIOS
    CONSTRAINT FUNC_TEL_FK_FUNCIONARIOS FOREIGN KEY(FUNC_MATRICULA) REFERENCES FUNCIONARIOS(FUNC_MATRICULA)
);

-- Tabela ENCOMENDAS
CREATE TABLE IF NOT EXISTS ENCOMENDAS (
	ENCOM_COD INT PRIMARY KEY,
    ENCOM_DATAINCLU DATE NOT NULL,
    CLI_COD INT NOT NULL,
    -- Chave estangeira vinda da tabela CLIENTES
    CONSTRAINT ENCOM_FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD)
);

-- Tabela PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
	PAG_ID INT PRIMARY KEY,
    PAG_VALORTOTAL DECIMAL(10, 3),
    PAG_VALORDESC DECIMAL(10, 3),
    PAG_VALORLIQ DECIMAL(10, 3),
    PAG_FORMAPAGAMENTO VARCHAR(45) NOT NULL,
    PAG_QTDPARCELAS VARCHAR(45),
    ENCOM_COD INT NOT NULL,
    -- Chave estangeira vinda da tabela ENCOMENDAS
    CONSTRAINT PAG_FK_ENCOMENDAS FOREIGN KEY(ENCOM_COD) REFERENCES ENCOMENDAS(ENCOM_COD)    
);

-- Tabela PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS (
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(100) NOT NULL,
    PROD_COR VARCHAR(45)  NOT NULL,
    PROD_PESO DECIMAL(10, 2) NOT NULL,
    PROD_PRECOUND DECIMAL(10, 2) NOT NULL,
    PROD_TEMPOFABRI TIME NOT NULL,
    PROD_DESENHOPROD VARCHAR(255) NOT NULL,
    PROD_HRMAOOBRA DECIMAL(10, 2) NOT NULL,
    PROD_ALTURA DECIMAL(10,3) NOT NULL,
    PROD_LARGURA DECIMAL(10,3) NOT NULL,
    PROD_COMPRIMENTO DECIMAL(10,3) NOT NULL
);

-- Tabela FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FORN_COD INT PRIMARY KEY,
    FORN_CNPJ VARCHAR(45) NOT NULL,
    FORN_RAZAOSOCIAL VARCHAR(45) NOT NULL,
    FORN_PCONTATO VARCHAR(45) NOT NULL,
    FORN_END_COD INT NOT NULL,
    -- Chave estangeira vinda da tabela ENDERECOS
    CONSTRAINT FORN_FK_ENDERECOS FOREIGN KEY(FORN_END_COD) REFERENCES ENDERECOS(END_COD)
);

-- Tabela TIPO_COMPONENTE
CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE (
	TIPO_COMP_COD INT PRIMARY KEY,
    TIPO_COMP_NOME VARCHAR(45) NOT NULL
);

-- Tabela COMPONENTES
CREATE TABLE IF NOT EXISTS COMPONENTES (
	COMP_COD INT PRIMARY KEY,
    COMP_NOME VARCHAR(45) NOT NULL,
    COMP_QTDESTOQUE INT NOT NULL,
    COMP_PRECOUND DECIMAL(10,2) NOT NULL,
    COMP_UNIDADE INT,
    TIPO_COMP_COD INT NOT NULL,
    -- Chave estrangeira vinda de TIPO_COMPONENTE
    CONSTRAINT COMP_FK_TIPO_COMP FOREIGN KEY(TIPO_COMP_COD) REFERENCES TIPO_COMPONENTE(TIPO_COMP_COD)
);

-- Tabela RS
CREATE TABLE IF NOT EXISTS RS (
	COMPONENTES_COMP_COD INT PRIMARY KEY,
    RS_QUANTIDADE INT NOT NULL,
    RS_DATANESC DATE NOT NULL,
    -- Chave estangeira vinda da tabela COMPONENTES
    CONSTRAINT RS_FK_COMPONENTES FOREIGN KEY(COMPONENTES_COMP_COD) REFERENCES COMPONENTES(COMP_COD)
);

-- Tabela associativa de FORNECEDORES <-> COMPONENTES
CREATE TABLE IF NOT EXISTS FORNECEDORES_COMPONENETES (
	COMP_COD INT,
    FORN_COD INT,
    PRIMARY KEY(COMP_COD, FORN_COD),
    -- Chave estangeira vinda da tabela FORNECEDORES
    CONSTRAINT FOCO_FK_FORNECEDORES FOREIGN KEY(FORN_COD) REFERENCES FORNECEDORES(FORN_COD),
    -- Chave estangeira vinda da tabela COMPONENTES
    CONSTRAINT FOCO_FK_COMPONENTES FOREIGN KEY(COMP_COD) REFERENCES COMPONENTES(COMP_COD)
);

-- Tabela MAQUINAS
CREATE TABLE IF NOT EXISTS MAQUINAS (
	MAQ_ID INT PRIMARY KEY,
	MAQ_TEMPOVIDA TIME NOT NULL,
    MAQ_DATACOMPRA DATE NOT NULL,
    MAQ_FIMGARANTIA DATE NOT NULL
);

-- Tabela RM
CREATE TABLE IF NOT EXISTS RM (
	RM_DATA DATE PRIMARY KEY,
    RM_DESCRICAO TEXT NOT NULL,
    MAQ_ID INT NOT NULL,
    -- Chave estangeira vinda da tabela MAQUINAS
    CONSTRAINT FK_MAQUINAS FOREIGN KEY(MAQ_ID) REFERENCES MAQUINAS(MAQ_ID)
 );
 
-- Tabela RE
CREATE TABLE IF NOT EXISTS RE (
	RE_COD INT PRIMARY KEY,
    PROD_COD INT NOT NULL,
    FUNC_COD INT NOT NULL,
    MAQ_ID INT NOT NULL,
    COMP_COD INT NOT NULL,
    RE_QTDCOMP INT NOT NULL,
    RE_UNDMEDIDA VARCHAR(45) NOT NULL,
    RE_TEMPOUSOMAQUINA VARCHAR(45) NOT NULL,
    RE_HRMAOOBRA VARCHAR(45),
    -- Chave estangeira vinda da tabela PRODUTOS
    CONSTRAINT RE_FK_PRODUTOS FOREIGN KEY(PROD_COD) REFERENCES PRODUTOS(PROD_COD),
    -- Chave estangeira vinda da tabela FUNCIONARIOS
    CONSTRAINT RE_FK_FUNCIONARIOS FOREIGN KEY(FUNC_COD) REFERENCES FUNCIONARIOS(FUNC_MATRICULA),
    -- Chave estangeira vinda da tabela MAQUINAS
    CONSTRAINT RE_FK_MAQUINAS FOREIGN KEY(MAQ_ID) REFERENCES MAQUINAS(MAQ_ID),
    -- Chave estangeira vinda da tabela COMPONENTES
    CONSTRAINT RE_FK_COMPONENTES FOREIGN KEY(COMP_COD) REFERENCES COMPONENTES(COMP_COD)
 );

-- ###################################################### --
-- ##################### ALTERS ######################### --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

--  ALTERS da tabela TIPO_ENDERECO

-- ADD COLUMN
ALTER TABLE TIPO_ENDERECO ADD TIPO_END_ATIVO BOOLEAN NOT NULL;

-- MODIFY COLUMN
ALTER TABLE TIPO_ENDERECO MODIFY COLUMN TIPO_END_ATIVO VARCHAR(50);

-- DROP COLUMN
ALTER TABLE TIPO_ENDERECO DROP COLUMN TIPO_END_ATIVO;

-- CHANGE COLUMN
ALTER TABLE TIPO_ENDERECO CHANGE COLUMN TIPO_END_CATEGORIA TIPO_END_CATEG VARCHAR(45);

-------------------------------------------------------------------------------

--  ALTERS da tabela ENDERECOS

-- ADD COLUMN
ALTER TABLE ENDERECOS ADD END_PAIS VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE ENDERECOS MODIFY COLUMN END_CEP VARCHAR(15);

-- DROP COLUMN
ALTER TABLE ENDERECOS DROP COLUMN END_PAIS;

-- CHANGE COLUMN
ALTER TABLE ENDERECOS CHANGE COLUMN END_NUM END_NUMLOGRADOURO VARCHAR(45);

-------------------------------------------------------------------------------

--  ALTERS da tabela EMPRESAS

-- ADD COLUMN
ALTER TABLE EMPRESAS ADD EMPRE_NOMEFANTASIA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE EMPRESAS MODIFY COLUMN EMPRE_PCONTATO VARCHAR(20);

-- DROP COLUMN
ALTER TABLE EMPRESAS DROP COLUMN EMPRE_NOMEFANTASIA;

-- CHANGE COLUMN
ALTER TABLE EMPRESAS CHANGE COLUMN EMPRE_PCONTATO EMPRE_PESSOACONTATO VARCHAR(20);

-------------------------------------------------------------------------------

--  ALTERS da tabela EMPRE_TEL

-- ADD COLUMN
ALTER TABLE EMPRE_TEL ADD EMPRE_TEL_DDD VARCHAR(3) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE EMPRE_TEL MODIFY COLUMN EMPRE_TEL_DDD INT;

-- DROP COLUMN
ALTER TABLE EMPRE_TEL DROP COLUMN EMPRE_TEL_DDD;

-- CHANGE COLUMN
ALTER TABLE EMPRE_TEL CHANGE COLUMN EMPRE_TEL_TELEFONE EMPRE_TEL_TEL VARCHAR(45);

-------------------------------------------------------------------------------

--  ALTERS da tabela CLIENTES

-- ADD COLUMN
ALTER TABLE CLIENTES ADD CLI_NOMEFANTASIA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CLIENTES MODIFY COLUMN CLI_NOMEFANTASIA VARCHAR(150);

-- CHANGE COLUMN
ALTER TABLE CLIENTES CHANGE COLUMN CLI_NOMEFANTASIA CLI_NOMEFANTASIA VARCHAR(45);

-- DROP COLUMN
ALTER TABLE CLIENTES DROP COLUMN CLI_NOMEFANTASIA;

-------------------------------------------------------------------------------

--  ALTERS da tabela CLIENTES

-- ADD COLUMN
ALTER TABLE CLIENTES ADD CLI_NOMEFANTASIA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CLIENTES MODIFY COLUMN CLI_NOMEFANTASIA VARCHAR(150);

-- CHANGE COLUMN
ALTER TABLE CLIENTES CHANGE COLUMN CLI_NOMEFANTASIA CLI_NOMEFANTASIA VARCHAR(45);

-- DROP COLUMN
ALTER TABLE CLIENTES DROP COLUMN CLI_NOMEFANTASIA;

-------------------------------------------------------------------------------

--  ALTERS da tabela CLI_TEL

-- ADD COLUMN
ALTER TABLE CLI_TEL ADD CLI_TEL_DDD VARCHAR(10) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CLI_TEL MODIFY COLUMN CLI_TEL_DDD INT;

-- CHANGE COLUMN
ALTER TABLE CLI_TEL CHANGE COLUMN CLI_TEL_DDD CLI_DDD INT;

-- DROP COLUMN
ALTER TABLE CLI_TEL DROP COLUMN CLI_DDD;

-------------------------------------------------------------------------------

--  ALTERS da tabela CLIENTES_ENDERECOS

-- ADD COLUMN
ALTER TABLE CLIENTES_ENDERECOS ADD CLI_END_ATIVO VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CLIENTES_ENDERECOS MODIFY COLUMN CLI_END_ATIVO BOOLEAN;

-- CHANGE COLUMN
ALTER TABLE CLIENTES_ENDERECOS CHANGE COLUMN CLI_END_ATIVO CLI_END_ESTAATIVO BOOLEAN;

-- DROP COLUMN
ALTER TABLE CLIENTES_ENDERECOS DROP COLUMN CLI_END_ESTAATIVO;

-------------------------------------------------------------------------------

--  ALTERS da tabela CARGOS

-- ADD COLUMN
ALTER TABLE CARGOS ADD CARGOS_DESCRICAO VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE CARGOS MODIFY COLUMN CARGOS_DESCRICAO TEXT;

-- CHANGE COLUMN
ALTER TABLE CARGOS CHANGE COLUMN CARGOS_DESCRICAO CARGO_DESC BOOLEAN;

-- DROP COLUMN
ALTER TABLE CARGOS DROP COLUMN CARGO_DESC;

-------------------------------------------------------------------------------

--  ALTERS da tabela FUNCIONARIOS

-- ADD COLUMN
ALTER TABLE FUNCIONARIOS ADD FUNC_SOBRENOME VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_SOBRENOME VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_SOBRENOME FUNC_SOBRENOMECOMPLETO VARCHAR(100);

-- DROP COLUMN
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_SOBRENOMECOMPLETO;

-------------------------------------------------------------------------------

--  ALTERS da tabela QUALIFICACOES

-- ADD COLUMN
ALTER TABLE QUALIFICACOES ADD QUALIFICACAO_DESCRICAO VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE QUALIFICACOES MODIFY COLUMN QUALIFICACAO_DESCRICAO TEXT;

-- CHANGE COLUMN
ALTER TABLE QUALIFICACOES CHANGE COLUMN QUALIFICACAO_DESCRICAO QUALIFICACAO_DESC TEXT;

-- DROP COLUMN
ALTER TABLE QUALIFICACOES DROP COLUMN QUALIFICACAO_DESC;

-------------------------------------------------------------------------------

--  ALTERS da tabela FUNC_TEL

-- ADD COLUMN
ALTER TABLE FUNC_TEL ADD FUNC_TEL_DDD VARCHAR(10) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FUNC_TEL MODIFY COLUMN FUNC_TEL_DDD INT;

-- CHANGE COLUMN
ALTER TABLE FUNC_TEL CHANGE COLUMN FUNC_TEL_DDD FUNC_DDD TEXT;

-- DROP COLUMN
ALTER TABLE FUNC_TEL DROP COLUMN FUNC_DDD;

-------------------------------------------------------------------------------

--  ALTERS da tabela ENCOMENDAS

-- ADD COLUMN
ALTER TABLE ENCOMENDAS ADD ENCOM_DESCRICAO VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE ENCOMENDAS MODIFY COLUMN ENCOM_DESCRICAO TEXT;

-- CHANGE COLUMN
ALTER TABLE ENCOMENDAS CHANGE COLUMN ENCOM_DESCRICAO ENCOM_DESC TEXT;

-- DROP COLUMN
ALTER TABLE ENCOMENDAS DROP COLUMN ENCOM_DESC;

-------------------------------------------------------------------------------

--  ALTERS da tabela PAGAMENTOS

-- ADD COLUMN
ALTER TABLE PAGAMENTOS ADD PAG_DATAPAGAMAENTO VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_DATAPAGAMAENTO DATE;

-- CHANGE COLUMN
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_DATAPAGAMAENTO PAG_DATAPAG TEXT;

-- DROP COLUMN
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_DATAPAG;

-------------------------------------------------------------------------------

--  ALTERS da tabela PRODUTOS

-- ADD COLUMN
ALTER TABLE PRODUTOS ADD PROD_ORIGEMPROD VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_ORIGEMPROD VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_ORIGEMPROD PROD_ORIGEM TEXT;

-- DROP COLUMN
ALTER TABLE PRODUTOS DROP COLUMN PROD_ORIGEM;

-------------------------------------------------------------------------------

--  ALTERS da tabela FORNECEDORES

-- ADD COLUMN
ALTER TABLE FORNECEDORES ADD FORN_PAIS VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES MODIFY COLUMN FORN_PAIS VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES CHANGE COLUMN FORN_PAIS FORN_PAISORIGEM TEXT;

-- DROP COLUMN
ALTER TABLE FORNECEDORES DROP COLUMN FORN_PAISORIGEM;

-------------------------------------------------------------------------------

--  ALTERS da tabela TIPO_COMPONENTE

-- ADD COLUMN
ALTER TABLE TIPO_COMPONENTE ADD COMP_DESCRICAO VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE TIPO_COMPONENTE MODIFY COLUMN COMP_DESCRICAO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE TIPO_COMPONENTE CHANGE COLUMN COMP_DESCRICAO COMP_DESC TEXT;

-- DROP COLUMN
ALTER TABLE TIPO_COMPONENTE DROP COLUMN COMP_DESC;

-------------------------------------------------------------------------------

--  ALTERS da tabela COMPONENTES

-- ADD COLUMN
ALTER TABLE COMPONENTES ADD COMP_DESCRICAO VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE COMPONENTES MODIFY COLUMN COMP_DESCRICAO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE COMPONENTES CHANGE COLUMN COMP_DESCRICAO COMP_DESC TEXT;

-- DROP COLUMN
ALTER TABLE COMPONENTES DROP COLUMN COMP_DESC;

-------------------------------------------------------------------------------

--  ALTERS da tabela RS

-- ADD COLUMN
ALTER TABLE RS ADD RS_DATA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE RS MODIFY COLUMN RS_DATA DATE;

-- CHANGE COLUMN
ALTER TABLE RS CHANGE COLUMN RS_DATA RS_DATAINCLU DATE;

-- DROP COLUMN
ALTER TABLE RS DROP COLUMN RS_DATAINCLU;

-------------------------------------------------------------------------------

--  ALTERS da tabela FORNECEDORES_COMPONENETES

-- ADD COLUMN
ALTER TABLE FORNECEDORES_COMPONENETES ADD FOCO_DATA VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE FORNECEDORES_COMPONENETES MODIFY COLUMN FOCO_DATA DATE;

-- CHANGE COLUMN
ALTER TABLE FORNECEDORES_COMPONENETES CHANGE COLUMN FOCO_DATA FRCO_DATA DATE;

-- DROP COLUMN
ALTER TABLE FORNECEDORES_COMPONENETES DROP COLUMN FRCO_DATA;

-------------------------------------------------------------------------------

--  ALTERS da tabela MAQUINAS

-- ADD COLUMN
ALTER TABLE MAQUINAS ADD MAQ_MODELO VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE MAQUINAS MODIFY COLUMN MAQ_MODELO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE MAQUINAS CHANGE COLUMN MAQ_MODELO MAQ_MODEL VARCHAR(100);

-- DROP COLUMN
ALTER TABLE MAQUINAS DROP COLUMN MAQ_MODEL;

-------------------------------------------------------------------------------

--  ALTERS da tabela RM

-- ADD COLUMN
ALTER TABLE RM ADD RM_HORA VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE RM MODIFY COLUMN RM_HORA TIME;

-- CHANGE COLUMN
ALTER TABLE RM CHANGE COLUMN RM_HORA RM_HR VARCHAR(100);

-- DROP COLUMN
ALTER TABLE RM DROP COLUMN RM_HR;

-------------------------------------------------------------------------------

--  ALTERS da tabela RE

-- ADD COLUMN
ALTER TABLE RE ADD RE_DIAS VARCHAR(20) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE RE MODIFY COLUMN RE_DIAS INT;

-- CHANGE COLUMN
ALTER TABLE RE CHANGE COLUMN RE_DIAS RE_DIA INT;

-- DROP COLUMN
ALTER TABLE RE DROP COLUMN RE_DIA;


-- ###################################################### --
-- ######################## DROP ######################## --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

DROP TABLE EMPRE_TEL;