CREATE SCHEMA EST_CASO_II;

USE EST_CASO_II;


--Criação das tabelas mais simples

-- Tabela PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
	PASS_CPF VARCHAR(14) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_RUA VARCHAR(100) NOT NULL,
	PASS_NUMRUA INT,
	PASS_BAIRRO VARCHAR(50) NOT NULL,
	PASS_CIDADE VARCHAR(50) NOT NULL,
	PASS_ESTADO VARCHAR(50) NOT NULL,
	PASS_PAIS VARCHAR(50) NOT NULL,
	PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_EMAIL VARCHAR(50) NOT NULL
);

-- Tabela FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	FUNC_ID INT PRIMARY KEY,
    FUNC_CPF VARCHAR(14) NOT NULL,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_RUA VARCHAR(100) NOT NULL,
    FUNC_NUMRUA INT,
    FUNC_BAIRRO VARCHAR(50) NOT NULL,
    FUNC_CIDADE VARCHAR(50) NOT NULL,
    FUNC_ESTADO VARCHAR(50) NOT NULL,
    FUNC_PAIS VARCHAR(50) NOT NULL,
    FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

-- Tabela AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES (
	AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_FABRICANTE VARCHAR(50) NOT NULL,
    AERON_ANOFABR YEAR NOT NULL,
    AERON_CAPACIDADE TEXT NOT NULL,
    AERON_AUTONOMIA VARCHAR(10) NOT NULL
);

-- Tabela AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS (
	AEROP_CODIGO INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(50) NOT NULL,
    AEROP_PAIS VARCHAR(50) NOT NULL,
    AEROP_LATITUDE TEXT NOT NULL,
    AEROP_LONGITUDE TEXT NOT NULL
);

-- Tabela VOOS
--Essa tabela contem duas FK vindas da tabela AEROPORTOS, onde uma é referente ao aeroporto de origem e a outra de destino
CREATE TABLE IF NOT EXISTS VOOS (
	VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVE VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROP_ORIGEM FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AEROP_DESTINO FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AERONAVE FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

-- Essa é a tabela assosiativa de VOOS <-> FUNCIONARIOS
CREATE TABLE IF NOT EXISTS EQUIPES (
	VOO_ID INT NOT NULL,
    FUNC_ID INT NOT NULL,
    PRIMARY KEY(VOO_ID, FUNC_ID),
    CONSTRAINT VOFU_FK_VOO FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID),
    CONSTRAINT VOFU_FK_FUNCIONARIO FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

-- Essa tabela recebe duas FKs. Uma de PASSAGEIROS e a outra de VOOS
CREATE TABLE IF NOT EXISTS RESERVAS (
	RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT NOT NULL,
    PASS_CPF VARCHAR(14) NOT NULL,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);


-- ###################################################### --
-- ##################### ALTERS ######################### --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --



--  ALTERS da tabela PASSAGEIROS

-- ADD COLUMN
ALTER TABLE PASSAGEIROS ADD PASS_NUMCELULAR VARCHAR(20) NOT NULL;

-- DROP COLUMN
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_TELEFONE;

-- MODIFY COLUMN
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_NOME VARCHAR(150);

-- CHANGE COLUMN
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_NOME PASS_NOMECOMPLETO VARCHAR(150);

----------------------------------------------------------------------------

--  ALTERS da tabela FUNCIONARIOS

-- ADD COLUMN
ALTER TABLE FUNCIONARIOS ADD FUNC_DATAADMISSAO DATE NOT NULL;

-- DROP COLUMN
ALTER TABLE FUNCIONARIOS DROP FUNC_CODPOSTAL;

-- MODIFY COLUMN
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_RUA VARCHAR(50);

-- CHANGE COLUMN
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_RUA FUNC_NUMRUA VARCHAR(50);

----------------------------------------------------------------------------

--  ALTERS da tabela FUNCIONARIOS

-- ADD COLUMN
ALTER TABLE FUNCIONARIOS ADD FUNC_DATAADMISSAO DATE NOT NULL;

-- DROP COLUMN
ALTER TABLE FUNCIONARIOS DROP FUNC_CODPOSTAL;

-- MODIFY COLUMN
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_RUA VARCHAR(50);

-- CHANGE COLUMN
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_RUA FUNC_NUMRUA VARCHAR(50);

----------------------------------------------------------------------------

--  ALTERS da tabela AERONAVES

-- ADD COLUMN
ALTER TABLE AERONAVES ADD AERON_QTDCOMBUSTIVEL DECIMAL(10, 3) NOT NULL;

-- DROP COLUMN
ALTER TABLE AERONAVES DROP AERON_AUTONOMIA;

-- MODIFY COLUMN
ALTER TABLE AERONAVES MODIFY COLUMN AERON_MODELO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE AERONAVES CHANGE COLUMN AERON_ANOFABR AERON_ANOFABRICACAO YEAR;

----------------------------------------------------------------------------

--  ALTERS da tabela AEROPORTOS

-- ADD COLUMN
ALTER TABLE AEROPORTOS ADD AEROP_NOMERESPONSAVEL VARCHAR(100) NOT NULL;

-- DROP COLUMN
ALTER TABLE AEROPORTOS DROP AEROP_CIDADE;

-- MODIFY COLUMN
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_NOME VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_NOME AEROP_NOMECOMPLETO VARCHAR(100);

----------------------------------------------------------------------------

--  ALTERS da tabela VOOS

-- ADD COLUMN
ALTER TABLE VOOS ADD VOO_ANO YEAR NOT NULL;

-- DROP COLUMN
ALTER TABLE VOOS DROP VOO_HORA;

-- MODIFY COLUMN
ALTER TABLE VOOS MODIFY COLUMN VOO_DATA VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE VOOS CHANGE COLUMN VOO_HORA VOO_HR TIME;

----------------------------------------------------------------------------

--  ALTERS da tabela EQUIPES

-- ADD COLUMN
ALTER TABLE EQUIPES ADD EQUIP_QUANTIDADE VARCHAR(100) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE EQUIPES MODIFY COLUMN EQUIP_QUANTIDADE INT;

-- CHANGE COLUMN
ALTER TABLE EQUIPES CHANGE COLUMN EQUIP_QUANTIDADE EQUIP_QTD INT;

-- DROP COLUMN
ALTER TABLE EQUIPES DROP EQUIP_QTD;


----------------------------------------------------------------------------

--  ALTERS da tabela RESERVAS

-- ADD COLUMN
ALTER TABLE RESERVAS ADD RESERVA_DATA DATE NOT NULL;

-- MODIFY COLUMN
ALTER TABLE RESERVAS MODIFY RESERVA_COD VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE RESERVAS CHANGE COLUMN RESERVA_COD RESERVA_CODIGO VARCHAR(100);

-- DROP COLUMN
ALTER TABLE RESERVAS DROP RESERVA_DATA;


-- ###################################################### --
-- ######################## DROP ######################## --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

DROP TABLE EQUIPES;