CREATE SCHEMA EST_CASO_IV;
USE EST_CASO_IV; 

-- Tabela ALUNOS
CREATE TABLE IF NOT EXISTS ALUNOS (
	ALUNO_ID INT PRIMARY KEY,
    ALUNO_CPF VARCHAR(14) NOT NULL,
    ALUNO_NOME VARCHAR(100) NOT NULL,
    ALUNO_DATANASC DATE NOT NULL,
    ALUNO_RUA VARCHAR(100) NOT NULL,
    ALUNO_NUM INT,
    ALUNO_COMPLEMENTO TEXT,
    ALUNO_BAIRRO VARCHAR(100) NOT NULL,
    ALUNO_CIDADE VARCHAR(100) NOT NULL,
    ALUNO_CEP VARCHAR(15) NOT NULL,
    ALUNO_UF CHAR(2) NOT NULL,
    ALUNO_PAIS VARCHAR(100) NOT NULL
);

-- Tabela INSTRUTORES
CREATE TABLE IF NOT EXISTS INSTRUTORES (
	INSTRU_ID INT PRIMARY KEY,
    INSTRU_CPF VARCHAR(14) NOT NULL,
    INSTRU_NOME VARCHAR(100) NOT NULL,
    INSTRU_DATANASC DATE NOT NULL,
	INSTRU_RUA VARCHAR(100) NOT NULL,
    INSTRU_NUM INT,
    INSTRU_COMPLEMENTO TEXT,
    INSTRU_BAIRRO VARCHAR(100) NOT NULL,
    INSTRU_CIDADE VARCHAR(100) NOT NULL,
    INSTRU_CEP VARCHAR(15) NOT NULL,
    INSTRU_UF CHAR(2) NOT NULL,
    INSTRU_PAIS VARCHAR(100) NOT NULL,
    INSTRU_ESPECIALIDADE VARCHAR(100) NOT NULL
);

-- Tabela MODALIDADES
CREATE TABLE IF NOT EXISTS MODALIDADES (
	MOD_ID INT PRIMARY KEY,
    MOD_NOME VARCHAR(100) NOT NULL,
    MOD_DESCRICAO TEXT NOT NULL
);

-- Tabela associativa entre PLANOS <-> TREINAMENTOS
CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTOS (
	PLAN_ID INT PRIMARY KEY,
    ALUNO_ID INT NOT NULL,
    INSTRU_ID INT NOT NULL,
    PLAN_DESCRICAO TEXT NOT NULL,
    PLAN_DATAINICIO DATE NOT NULL,
    PLAN_DATAFIM DATE,
    -- FK vinda da tabela ALUNOS
    CONSTRAINT PLTR_FK_ALUNO FOREIGN KEY(ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID),
    -- FK vinda da tabela INSTRUTOR
    CONSTRAINT PLTR_FK_INSTRUTOR FOREIGN KEY(INSTRU_ID) REFERENCES INSTRUTORES(INSTRU_ID)
);

-- Tabela AULAS
CREATE TABLE IF NOT EXISTS AULAS (
	AULA_ID INT PRIMARY KEY,
    MOD_ID INT NOT NULL,
    INSTRU_ID INT NOT NULL,
    AULA_HORARIO TIME NOT NULL,
    AULA_CAPACIDADE INT NOT NULL,
    -- FK vinda da tabela MODALIDADES
	CONSTRAINT AULAS_FK_MODALIDADES FOREIGN KEY (MOD_ID) REFERENCES MODALIDADES(MOD_ID),
    -- FK vinda da tabela INSTRUTORES
    CONSTRAINT AULAS_FK_INSTRUTORES FOREIGN KEY (INSTRU_ID) REFERENCES INSTRUTORES(INSTRU_ID)
);

-- Tabela MATRICULAS
CREATE TABLE IF NOT EXISTS MATRICULAS (
	MATRICULA_ID INT PRIMARY KEY,
    ALUNO_ID INT NOT NULL,
    MOD_ID INT NOT NULL,
    MATRICULA_DATA DATE NOT NULL,
    MATRICULA_STATUS ENUM("MATRICULADO", "NAO MATRICULADO"),
    -- FK vinda da tabela ALUNOS
    CONSTRAINT MATRICULA_FK_ALUNOS FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID),
    -- FK vinda da tabela MODALIDADES
    CONSTRAINT MATRICULA_FK_MODALIDADES FOREIGN KEY (MOD_ID) REFERENCES MODALIDADES(MOD_ID)
);

-- Tabela PAGAMENTOS
CREATE TABLE IF NOT EXISTS PAGAMENTOS (
	PAG_ID INT PRIMARY KEY,
    MATRICULA_ID INT NOT NULL,
    PAG_DATA DATE NOT NULL,
    PAG_VALOR DECIMAL(10, 3) NOT NULL,
    PAG_STATUS ENUM("PAGO", "PENDENTE"),
    -- FK vinda da tabela MATRICULAS
    CONSTRAINT PAG_FK_MATRICULAS FOREIGN KEY(MATRICULA_ID) REFERENCES MATRICULAS(MATRICULA_ID)
);

-- Entidade associativa entre ALUNOS <-> AULAS
CREATE TABLE IF NOT EXISTS ALUNOS_AULAS (
	AULA_ID INT,
    ALUNO_ID INT,
    PRIMARY KEY(AULA_ID, ALUNO_ID),
    -- FK vinda da tabela AULAS
    CONSTRAINT ALAU_FK_AULAS FOREIGN KEY(AULA_ID) REFERENCES AULAS(AULA_ID),
    -- FK vinda da tabela ALUNOS    
    CONSTRAINT ALAU_FK_ALUNOS FOREIGN KEY(ALUNO_ID) REFERENCES ALUNOS(ALUNO_ID) 
);

-- ###################################################### --
-- ##################### ALTERS ######################### --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

--  ALTERS da tabela ALUNOS

-- ADD COLUMN
ALTER TABLE ALUNOS ADD ALUNO_NOMEMAE VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE ALUNOS MODIFY COLUMN ALUNO_NOMEMAE VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE ALUNOS CHANGE COLUMN ALUNO_NOMEMAE ALUNO_MAE VARCHAR(100);

-- DROP COLUMN
ALTER TABLE ALUNOS DROP COLUMN ALUNO_MAE;

-------------------------------------------------------------------------------

--  ALTERS da tabela INSTRUTORES

-- ADD COLUMN
ALTER TABLE INSTRUTORES ADD INSTRU_RG VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE INSTRUTORES MODIFY COLUMN INSTRU_RG VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE INSTRUTORES CHANGE COLUMN INSTRU_RG INSTRU_REGISTROGERAL VARCHAR(100);

-- DROP COLUMN
ALTER TABLE INSTRUTORES DROP COLUMN INSTRU_REGISTROGERAL;

-------------------------------------------------------------------------------

--  ALTERS da tabela MODALIDADES

-- ADD COLUMN
ALTER TABLE MODALIDADES ADD MOD_ATIVA VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE MODALIDADES MODIFY COLUMN MOD_ATIVA BOOLEAN;

-- CHANGE COLUMN
ALTER TABLE MODALIDADES CHANGE COLUMN MOD_ATIVA MOD_ESTAATIVA BOOLEAN;

-- DROP COLUMN
ALTER TABLE MODALIDADES DROP COLUMN MOD_ESTAATIVA;

-------------------------------------------------------------------------------

--  ALTERS da tabela PLANOS_TREINAMENTOS

-- ADD COLUMN
ALTER TABLE PLANOS_TREINAMENTOS ADD PLANO_QTDHORAS VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PLANOS_TREINAMENTOS MODIFY COLUMN PLANO_QTDHORAS TIME;

-- CHANGE COLUMN
ALTER TABLE PLANOS_TREINAMENTOS CHANGE COLUMN PLANO_QTDHORAS PLANO_QUANTIDADEHORA BOOLEAN;

-- DROP COLUMN
ALTER TABLE PLANOS_TREINAMENTOS DROP COLUMN PLANO_QUANTIDADEHORA;

-------------------------------------------------------------------------------

--  ALTERS da tabela AULAS

-- ADD COLUMN
ALTER TABLE AULAS ADD AULA_TURNO VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE AULAS MODIFY COLUMN AULA_TURNO VARCHAR(100);

-- CHANGE COLUMN
ALTER TABLE AULAS CHANGE COLUMN AULA_TURNO AULA_HRTURNO VARCHAR(100);

-- DROP COLUMN
ALTER TABLE AULAS DROP COLUMN AULA_HRTURNO;

-------------------------------------------------------------------------------

--  ALTERS da tabela MATRICULAS

-- ADD COLUMN
ALTER TABLE MATRICULAS ADD MATRICULA_HR VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE MATRICULAS MODIFY COLUMN MATRICULA_HR TIME;

-- CHANGE COLUMN
ALTER TABLE MATRICULAS CHANGE COLUMN MATRICULA_HR MATRICULA_HORA TIME;

-- DROP COLUMN
ALTER TABLE MATRICULAS DROP COLUMN MATRICULA_HORA;

-------------------------------------------------------------------------------

--  ALTERS da tabela PAGAMENTOS

-- ADD COLUMN
ALTER TABLE PAGAMENTOS ADD PAG_MODALIDADE VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE PAGAMENTOS MODIFY COLUMN PAG_MODALIDADE ENUM("PIX", "CREDITO", "DEBITO", "BOLETO");

-- CHANGE COLUMN
ALTER TABLE PAGAMENTOS CHANGE COLUMN PAG_MODALIDADE PAG_MOD ENUM("PIX", "CREDITO", "DEBITO", "BOLETO");

-- DROP COLUMN
ALTER TABLE PAGAMENTOS DROP COLUMN PAG_MOD;

-------------------------------------------------------------------------------

--  ALTERS da tabela ALUNOS_AULAS

-- ADD COLUMN
ALTER TABLE ALUNOS_AULAS ADD ALAU_HORA VARCHAR(50) NOT NULL;

-- MODIFY COLUMN
ALTER TABLE ALUNOS_AULAS MODIFY COLUMN ALAU_HORA TIME;

-- CHANGE COLUMN
ALTER TABLE ALUNOS_AULAS CHANGE COLUMN ALAU_HORA ALUNO_AULAS_HR TIME;

-- DROP COLUMN
ALTER TABLE ALUNOS_AULAS DROP COLUMN ALUNO_AULAS_HR;


-- ###################################################### --
-- ######################## DROP ######################## --
-- ###################################################### --

-- ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ --

DROP TABLE PAGAMENTOS;